修改詞典，略改 hkcantonese.schema.yaml
rime/rime-jyutping pull request #20
Opened 2019-10-10 18:47 UTC by szc126

2019-10-10 20:58 UTC, laubonghaudoi requested changes

2019-10-10 20:58 UTC, laubonghaudoi commented on jyutping.dict.yaml
> +翻工
用“翻”定係“返”目前未有定論，建議兩個都保留。下面幾個修改都係。

2019-10-10 20:58 UTC, laubonghaudoi commented on jyutping.dict.yaml
> +呢種人	ni zung jan
呢一部分唔建議修改，可能需要開一個issue來討論。因爲呢隻字嘅發音目前未有確定，根據廣州話正音字典，呢隻字做指示代詞嗰陣既可以讀nei亦都可以讀ni。有種解決辦法係，將個「呢」字嘅單字讀音包括晒nei1 ni1 ne1三種音，然後詞組唔標示讀音。

2019-10-10 20:58 UTC, laubonghaudoi commented on hkcantonese.schema.yaml
>      https://github.com/rime/rime-jyutping
```suggestion
    https://zh.wikipedia.org/wiki/%E9%A6%99%E6%B8%AF%E6%94%BF%E5%BA%9C%E7%B2%B5%E8%AA%9E%E6%8B%BC%E9%9F%B3
```

2019-10-10 22:38 UTC, szc126 commented on jyutping.dict.yaml
> +翻工
其實我自己係中意用「返」嘅，但詞句嘅大部分好似係已經用緊「翻」。

2019-10-10 22:45 UTC, szc126 commented on jyutping.dict.yaml
> +呢種人	ni zung jan
如上面嘅「返」，我偏向讀「nei1」，但詞典內已經係標成「呢 ni1」🙈
同「嚟」一樣把啲讀音刪咗去吧。

2019-10-10 22:55 UTC, laubonghaudoi commented on jyutping.dict.yaml
> +呢種人	ni zung jan
好，噉你將呢道嘅「呢」字全部改成nei？

2019-10-11 16:42 UTC, laubonghaudoi commented
@szc126 可唔可以做以下修改，然後我再merge：
1. 將「呢」嘅發音全部改成nei
2. 所有嘅faan字統一爲「返」

2019-10-11 17:00 UTC, sgalal commented
我哋係唔係已經確定咗「返」好過「翻」？

2019-10-11 17:07 UTC, laubonghaudoi commented
> 我哋係唔係已經確定咗「返」好過「翻」？

目前未有統一嘅正字方案，所以其實寫兩個都得。

2019-10-12 03:55 UTC, sgalal reviewed
這種不是詞的條目，是否應該刪去？

2019-10-12 04:03 UTC, szc126 commented
> 這種不是詞的條目，是否應該刪去？

@LEOYoon-Tsaw (rime/brise@3a7aebe).

2019-10-12 04:38 UTC, laubonghaudoi approved these changes

2019-10-12 04:40 UTC, merged