Update jyutping.dict.yaml
rime/rime-jyutping pull request #8
Opened 2018-04-16 14:22 UTC by LimTo

2018-04-17 14:58 UTC, lotem requested changes
夾用英文的拼寫問題，還需討論

2018-04-17 14:58 UTC, lotem commented on jyutping.dict.yaml
> +開O.T.	hoi ot
非粵語拼音原則上不應加入韻書，會破壞音節表的規律性，影響使用簡拼。
這一例就很可疑。因爲加入了 `ot` 音節，簡拼 `o't` 可能無法輸入。

如果不必要收錄，可以刪除這類詞彙。或者集中起來另建一部韻書，以免影響正常的粵拼輸入。

2018-04-17 14:58 UTC, lotem commented on jyutping.dict.yaml
> +好high	hou hai
`hai` 還是 `haai`?

這類轉寫成粵拼音節的外文，對輸入中文不會造成影響。

2018-04-17 14:58 UTC, lotem commented on jyutping.dict.yaml
> +X光	x gwong
`x` 恰好粵拼不用，否則影響簡拼。

2019-09-12 00:18 UTC, laubonghaudoi commented on jyutping.dict.yaml
> +好high	hou hai
可以確定是haai
```suggestion
好high	hou haai
```

2019-09-12 00:19 UTC, laubonghaudoi commented
想借此問一下，碼表中是否應該杜絕中英夾雜的詞彙？

2019-09-12 04:22 UTC, lotem commented
> 想借此問一下，碼表中是否應該杜絕中英夾雜的詞彙？

是的。
容易引入音系之外的拼寫。
最好另闢一個詞典收錄這些詞彙。

2019-09-23 02:59 UTC, chillgoor commented
好鬼死難頂	hou gwai sei laan ding
經過睇到，難應該係naan

2019-09-23 03:37 UTC, laubonghaudoi commented
> 好鬼死難頂 hou gwai sei laan ding
> 經過睇到，難應該係naan

多謝反饋，我下次更新會修復。目前呢個倉庫主要由我來維護，有咩bug同意見都可以搵我，好多謝你嘅幫手。

2019-10-02 18:01 UTC, closed without merging